# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipster', '0002_auto_20160716_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('has_disbursed', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(b'visible', b'Visible'), (b'deleted by user', b'Deleted by user'), (b'deleted by admin', b'Deleted by admin')], default=b'visible', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upvote_balance',
            field=models.BigIntegerField(help_text=b'The balance from upvotes only'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipster.Post'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
