# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipster', '0004_deposit_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[(b'submitted', b'Submitted'), (b'approved', b'Approved'), (b'denied', b'Denied'), (b'executed', b'Executed')], default=b'submitted', max_length=50),
        ),
    ]
