# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipster', '0005_auto_20160716_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='upvote_balance',
            field=models.BigIntegerField(default=0, help_text=b'The balance from upvotes only'),
        ),
    ]
